
services:
  nginx:
    ports:
      - "80:80"
    depends_on:
      - node-app-container
    networks:
      - app-network

  node-app-container:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER} 
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
    networks:
      - app-network

  database:
      environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      networks:
        - app-network
  redis:
      networks:
        - app-network

networks:
  app-network: