
services:

  nginx:
    image: nginx:latest   
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app-container:
    build: .
    environment:
      - MONGO_IP=database
      - MONGO_PORT=27017
      - PORT=3000
    depends_on:
      - database

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: firstroot
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis


volumes:
  mongo-db:
  

